### ISSUE TITLE
调色板弄个保存颜色（？）

### ISSUE THREAD

**Issue by undefined303** [bczhc/some-tools#130]
导出时候一并导出了，没有保存的就不显示最下面那栏
![2020-04-17_21 39 44](https://user-images.githubusercontent.com/54739035/79575194-edc60b00-80b0-11ea-9941-c5185ae3477e.jpg)

**Comment by bczhc** [comment]
3f9d3197b9f8ffbf4639ebabd1dbc4a9dca4db4c d84097fb136ca029780e7b1ac41c89bae61a7200 41bc79cbb6b5009c62fa696d16d475f4964a704a

**Comment by undefined303** [comment]
保存颜色后选中颜色，hsva的条没动

**Comment by bczhc** [comment]
d818f0bee50ba5e46cdb4d32980807941d0fb13b
