### ISSUE TITLE
画板取色 Android10 异常

### ISSUE THREAD

**Issue by bczhc** [bczhc/some-tools#151]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7, result=-1, data=Intent { (has extras) }} to activity {pers.zhc.tools/pers.zhc.tools.floatingdrawing.RequestCaptureScreenActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION	at android.app.ActivityThread.deliverResults(ActivityThread.java:5557)	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5598)	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)	at android.os.Handler.dispatchMessage(Handler.java:110)	at android.os.Looper.loop(Looper.java:219)	at android.app.ActivityThread.main(ActivityThread.java:8293)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION	at android.os.Parcel.createException(Parcel.java:2071)	at android.os.Parcel.readException(Parcel.java:2039)	at android.os.Parcel.readException(Parcel.java:1987)	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)	at android.media.projection.MediaProjection.<init>(MediaProjection.java:75)	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)	at pers.zhc.tools.floatingdrawing.FloatingDrawingBoardMainActivity.setupProjection(FloatingDrawingBoardMainActivity.java:621)	at pers.zhc.tools.floatingdrawing.FloatingDrawingBoardMainActivity.lambda$init$15$FloatingDrawingBoardMainActivity(FloatingDrawingBoardMainActivity.java:476)	at pers.zhc.tools.floatingdrawing.-$$Lambda$FloatingDrawingBoardMainActivity$0PmZbHUU2E1kuidSbECPTr2pU9s.onRequestCallback(Unknown Source:2)	at pers.zhc.tools.floatingdrawing.RequestCaptureScreenActivity.onActivityResult(RequestCaptureScreenActivity.java:49)	at android.app.Activity.dispatchActivityResult(Activity.java:8412)	at android.app.ActivityThread.deliverResults(ActivityThread.java:5550)	... 11 moreCaused by: android.os.RemoteException: Remote stack trace:	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(libmapleservices.so:16276444)	at android.media.projection.IMediaProjection$Stub.onTransact(libmapleframework.so:18648620)	at android.os.Binder.execTransactInternal(libmapleframework.so:5520792)	at android.os.Binder.execTransact(libmapleframework.so:5520004)java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION	at android.os.Parcel.createException(Parcel.java:2071)	at android.os.Parcel.readException(Parcel.java:2039)	at android.os.Parcel.readException(Parcel.java:1987)	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)	at android.media.projection.MediaProjection.<init>(MediaProjection.java:75)	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)	at pers.zhc.tools.floatingdrawing.FloatingDrawingBoardMainActivity.setupProjection(FloatingDrawingBoardMainActivity.java:621)	at pers.zhc.tools.floatingdrawing.FloatingDrawingBoardMainActivity.lambda$init$15$FloatingDrawingBoardMainActivity(FloatingDrawingBoardMainActivity.java:476)	at pers.zhc.tools.floatingdrawing.-$$Lambda$FloatingDrawingBoardMainActivity$0PmZbHUU2E1kuidSbECPTr2pU9s.onRequestCallback(Unknown Source:2)	at pers.zhc.tools.floatingdrawing.RequestCaptureScreenActivity.onActivityResult(RequestCaptureScreenActivity.java:49)	at android.app.Activity.dispatchActivityResult(Activity.java:8412)	at android.app.ActivityThread.deliverResults(ActivityThread.java:5550)	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5598)	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)	at android.os.Handler.dispatchMessage(Handler.java:110)	at android.os.Looper.loop(Looper.java:219)	at android.app.ActivityThread.main(ActivityThread.java:8293)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)Caused by: android.os.RemoteException: Remote stack trace:	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(libmapleservices.so:16276444)	at android.media.projection.IMediaProjection$Stub.onTransact(libmapleframework.so:18648620)	at android.os.Binder.execTransactInternal(libmapleframework.so:5520792)	at android.os.Binder.execTransact(libmapleframework.so:5520004)android.os.RemoteException: Remote stack trace:	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(libmapleservices.so:16276444)	at android.media.projection.IMediaProjection$Stub.onTransact(libmapleframework.so:18648620)	at android.os.Binder.execTransactInternal(libmapleframework.so:5520792)	at android.os.Binder.execTransact(libmapleframework.so:5520004)

**Comment by undefined303** [comment]
虚拟机android7测试也异常（android10测试异常崩溃后，再打开画板，点击取色，所点击的取色对应的画板图标会消失）

**Comment by bczhc** [comment]
76b9a9c9228ef42fd653bfef1cf99345dc96ba71
