### ISSUE TITLE
快捷方式问题

### ISSUE THREAD

**Issue by undefined303** [bczhc/some-tools#170]
1.绿色图标#127
2.未打开应用时打开快捷方式无法打开
3.快捷方式打开仍然和正常软件图标打开一样
4.主页长按1次创建快捷方式，两次是在那一栏移除（如果这是对的话），那么第二次长按还显示创建成功就是bug了

**Comment by bczhc** [comment]
>2.未打开应用时打开快捷方式无法打开
>3.快捷方式打开仍然和正常软件图标打开一样

?????

**Comment by undefined303** [comment]
2.3.好像只有笔记快捷方式有问题

**Comment by bczhc** [comment]
> 主页长按1次创建快捷方式，两次是在那一栏移除（如果这是对的话），那么第二次长按还显示创建成功就是bug了
