### ISSUE TITLE
现在设置默认变换好像是不能导出的

### ISSUE THREAD

**Issue by undefined303** [bczhc/some-tools#233]
（修复后可能出现的问题：不知道导入多个设置不同默认变换的会不会出问题，按道理如果左边全部是相对一个坐标原点，应该没有问题）

**Comment by undefined303** [comment]
现在是有重置默认变换的，如果我的理解没有问题应该是相当于将坐标进行一系列变换，(x,y)→f(x,y)，变换后为f(x,y)，设为默认变换即原点用f(0,0)替换，重置默认变换就是重新使用(0,0)为原点及(x,y)绘制
对于导出默认变化，我的想法：将f(0，0）直接作为原点重新计算，丢失原始默认变换信息 这样所有的导入均相对于新画布（待导入）的原点了

**Comment by bczhc** [comment]
引入bug的commit： 4a0bceec647abd6de6d813e59835b59276f1a421

嗯关于导入不同变换path会出现的问题之后再放到新的issue里吧，先记录着
