### ISSUE TITLE
保持activity不退出，悬浮窗 退出 隐藏和通知点击相配合，出现各种bug..

### ISSUE THREAD

**Issue by bczhc** [bczhc/some-tools#33]
优化界面逻辑

**Comment by undefined303** [comment]
好了#9，#10也可以close了。。。

**Comment by bczhc** [comment]
打开应用→开启悬浮窗→点击画板图标→点击隐藏按钮→关闭悬浮窗→开启悬浮窗→（产生一个画板图标）→下滑通知栏→显示悬浮窗（取消隐藏）→（产生一个画板图标），这俩个悬浮窗有问题（反正按按就闪退了）


打开应用→开启悬浮窗→点击画板图标→点击退出按钮→关闭悬浮窗→开启悬浮窗→点击隐藏按钮→下滑通知栏→显示悬浮窗（取消隐藏）→（不产生画板图标）

**Comment by bczhc** [comment]
。。所以隐藏那个绘画状态在还原的时候加一句换成绘画状态再取消隐藏还是不行吗。。

状态绘画→（操作）隐藏→（操作）点击通知栏→改为画板绘画状态&&操作按钮改为绘画→取消隐藏

**Comment by bczhc** [comment]
貌似现在没问题了。。
