### ISSUE TITLE
横屏一些显示问题（？）

### ISSUE THREAD

**Issue by undefined303** [bczhc/some-tools#57]
➣横屏导出路径/图片键盘不自动弹出（有全选）
➣横屏崩溃退出上传按钮不显示

**Comment by bczhc** [comment]
> ➣横屏导出路径/图片键盘不自动弹出（有全选）
> ➣横屏崩溃退出上传按钮不显示

?好像这个不会吧。。

**Comment by undefined303** [comment]
> > ➣横屏导出路径/图片键盘不自动弹出（有全选）
> > ➣横屏崩溃退出上传按钮不显示
> 
> ?好像这个不会吧。。

崩溃没事了，现在不是弹窗了，导出键盘是有问题的。。。
![Screenshot_20200510_195152_mark via](https://user-images.githubusercontent.com/54739035/81498473-cf41e100-92f7-11ea-997b-5391143a7428.jpg)
