### ISSUE TITLE
画板覆盖在操作栏上bug

### ISSUE THREAD

**Issue by undefined303** [bczhc/some-tools#66]
具体操作：
打开软件（杀掉后）>打开悬浮窗>隐藏>关闭悬浮窗>取消隐藏>打开悬浮窗>设置绘画模式

**Comment by bczhc** [comment]
> 具体操作：
> 打开软件（杀掉后）>打开悬浮窗>隐藏>关闭悬浮窗>取消隐藏>打开悬浮窗>设置绘画模式

这个bug应该以前版本也有吧。。
