### ISSUE TITLE
（其他输入框有一下瞎写会崩溃）（这个不改就直接close了吧😂）

### ISSUE THREAD

**Issue by undefined303** [bczhc/some-tools#88]
傅里叶那个上面的输入框瞎写了按+，崩溃报告是横屏的

**Comment by bczhc** [comment]
？崩溃报告是横屏的？？

![S00227-111105](https://user-images.githubusercontent.com/49330580/75408838-eeb0ab00-5951-11ea-828a-19b3e7f1091a.jpg)

**Comment by undefined303** [comment]
先+几个按开始，然后退出来，瞎写按+，崩溃就是横屏的

> ？崩溃报告是横屏的？？
> 
> ![S00227-111105](https://user-images.githubusercontent.com/49330580/75408838-eeb0ab00-5951-11ea-828a-19b3e7f1091a.jpg)
