### ISSUE TITLE
小bug。。傅里叶输参数（最上面那个）第一个括号是上标的

### ISSUE THREAD

**Issue by undefined303** [bczhc/some-tools#92]

**Comment by bczhc** [comment]
布局有点问题。。

![2b59cb45a9b68384](https://user-images.githubusercontent.com/49330580/75409705-77304b00-5954-11ea-9c4b-e6cd026be933.jpg)

![-2968702a1b57dad8](https://user-images.githubusercontent.com/49330580/75409721-84e5d080-5954-11ea-85c6-ceb29ceeeffc.jpg)
