### ISSUE TITLE
傅里叶按开始了要点一下才开始绘图

### ISSUE THREAD

**Issue by undefined303** [bczhc/some-tools#96]

**Comment by bczhc** [comment]
特性。。。

其实现在还没有完成，用SerfaceView就不会了，之前好的时候是一进去，显示的是所有本轮的初始情况，然后点击一下屏幕开始动画绘制……………………………………之后完成的话也会恢复这样的效果

**Comment by bczhc** [comment]
新的傅里叶不会了……
